### ISSUE TITLE
Missing filter growBounds

### ISSUE THREAD

**Issue by gogoprog** [FishingCactus/openfl#194]
It seems we miss a growBounds here :

```cpp
    private function __getBounds (rect:Rectangle):Void {

		if (__graphics != null) {

			__graphics.__getBounds (rect);

		} else {

			rect.setEmpty ();

		}

               //  this one :
		if (__filters != null) {
			@:privateAccess BitmapFilter.__expandBounds (__filters, rect, Matrix.__identity);
		}
	}
```

This needs to be discussed

**Comment by NuclearCookie** [comment]
A bit more context ( so we don't forget )
There's an issue with the bounds size we calculate in cacheAsBitmap.
Imagine this structure:

```
MovieClip --> flagged CacheAsBitmap = true
- MovieClip + Filter
-- ...
--- Shape
```
The computed bounds would be the bounds of the graphics ( Shape ).
In UpdateCacheBitmapFn() we account for the filter bounds of the top level element, but not of the children. So the result is that the bounds of the filters are not taken in to account.

For now the only issue we see is a cut bitmap, but this might potentially be a problem when using the bounds for hittest.
